spring:  
  datasource:
    url: jdbc:mysql://localhost:3306/demo?characterEncoding=utf-8&characterSetResults=utf-8&useUnicode=true&useSSL=true
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
  #配置redis缓存
  redis: 
    database: 1
    host: localhost
    password: 123456
    port: 6379
    max-idle: 8
    max-active: 8
    max-wait: -1
    min-idle: 0
    timeout: 0